[package]
name = "glacier"
version = "0.1.0"
authors = ["Yakup Budanaz <yakup.paradox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[test]]
name = "integration"
path = "tests/test.rs"

[dependencies]
